# Copyright (c) 2024, NVIDIA CORPORATION.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/cpplint/cpplint
    rev: 1.6.1
    hooks:
      - id: cpplint
        args: ["--recursive"]
  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v0.0.3
    hooks:
      - id: verify-copyright
        args: ["--fix", "--main-branch", "main"]


default_language_version:
      python: python3
